title: Research Website
author: Benjamin FitzGerald
email: bfitzgerald4@wisc.edu
description: >- # this means to ignore newlines until the next key
  This is my simple website powered by Jekyll.
baseurl: "" # the subpath of your site (if it's hosted in a subfolder)
url: "https://blfitzgerald.github.io" # the base hostname (GitHub Pages URL)

# Build settings
theme: minima # Default Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
