title: Research Website
author: Benjamin FitzGerald
email: bfitzgerald4@wisc.edu
description: >- # this means to ignore newlines until the next key
  Benjamin FitzGerald's website on his research.
baseurl: "" # the subpath of your site (if it's hosted in a subfolder)
url: "https://blfitzgerald.github.io" # the base hostname (GitHub Pages URL)

# Build settings
theme: jekyll-theme-minimal # Default Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
